
test: main.c ternaryHuffmanTree.c codeBook.c frequencyList.c helpers.c canonicalCodeBook.c nodeQueue.c 
	gcc main.c frequencyList.c codeBook.c ternaryHuffmanTree.c helpers.c canonicalCodeBook.c nodeQueue.c -o test

test2: main2.c ternaryHuffmanTree.c codeBook.c frequencyList.c helpers.c nodeQueue.c   
	gcc main2.c frequencyList.c codeBook.c ternaryHuffmanTree.c helpers.c nodeQueue.c -o test2

